services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    image: mariadb:notlatest
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx:notlatest
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    ports:
      - "443:443"
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress:notlatest
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    expose:
      - "9000"
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:custom
    networks:
      - inception
    ports:
      - "8080:8080"
    restart: always
  resume:
    container_name: resume
    build: ./requirements/bonus/resume_website
    image: resume:notlatest
    networks:
      - inception
    ports:
      - "8085:80"
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    image: cadvisor:42
    ports:
      - "3000:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge