services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: ./requirements/mariadb
    image: mariadb:notlatest
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: always
  nginx:
    container_name: nginx
    env_file:
      - .env
    build: ./requirements/nginx
    image: nginx:notlatest
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: always
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    build: ./requirements/wordpress
    image: wordpress:notlatest
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
    restart: always
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    networks:
      - inception
    expose:
      - "6379"
  # adminer:
  #   container_name: adminer
  #   build: ./requirements/bonus/adminer
  #   image: adminer:custom
  #   networks:
  #     - inception
  #   ports:
  #     - "8080:8080"
  #   restart: always
  # resume:
  #   container_name: resume
  #   build: ./requirements/bonus/resume_website
  #   image: resume:notlatest
  #   networks:
  #     - inception
  #   ports:
  #     - "8085:80"
  # cadvisor:
  #   container_name: cadvisor
  #   build: ./requirements/bonus/cadvisor/.
  #   image: cadvisor:42
  #   ports:
  #     - "3000:8080"
  #   networks:
  #     - inception
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro 
  #     - /sys:/sys:ro 
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/fbazaz/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/fbazaz/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge