services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    image: mariadb:notlatest
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"
  
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx:notlatest
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      # - redis
    build: ./requirements/wordpress
    image: wordpress:notlatest
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    expose:
      - "9000"
  # redis:
  #   container_name: redis
  #   build: ./requirements/bonus/redis
  #   networks:
  #     - inception
  #   expose:
  #     - 6379
  #   restart: always
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:custom
    networks:
      - inception
    ports:
      - "8080:8080"
    restart: always
  resume:
    container_name: resume
    build: ./requirements/bonus/resume_website
    image: resume:notlatest
    networks:
      - inception
    # volumes:
    #   - static_site:/usr/share/nginx/html
    ports:
      - "8085:80"
  
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb  # Host path for the MariaDB volume
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wordpress  # Host path for the WordPress files
      o: bind
  # static_site:

networks:
  inception:
    driver: bridge